<?php

$getId = $this->getRequest()->getParam('id');
$_shipment = Mage::getModel('customshipping/shipment')->load($getId)->getData();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Destination'); ?></h4>
    </div>
    <div class="fieldset">
        <div style="overflow:auto;">
            <table cellspacing="0" class="form-list">
                <tr>

                    <td class="label" colspan="2"><label><?php // echo $this->__('warehouse'); ?></label></td>
                    <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                        <td class="value"><input type="hidden" id="selected-wahehouseid" name="selected-wahehouseid" value="0" class="input-text" /></td>


                <?php endif; ?>


                <tr>
                    <input type="hidden" name="orderid" id="orderid" value="<?php echo $_shipment['order_id']; ?>"  />
                    <td class="label" colspan="2"><label><?php echo $this->__('Contact Name'); ?></label></td>
                    <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                        <td class="value"><input type="text" id="destination_contact_name" name="destination_contact_name" value="<?php echo $_shipment['destination_contact_name']; ?>" class="input-text" /></td>
                    <?php else: ?>
                    <td class="value"><?php echo $_shipment['destination_contact_name']; ?></td></tr>
                <?php endif; ?>

                <tr>
                    <td class="label" colspan="2"><label><?php echo $this->__('Company Name'); ?></label></td>
                    <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                        <td class="value"><input type="text" id="destination_company_name" name="destination_company_name" value="<?php echo $_shipment['destination_company_name']; ?>" class="input-text" /></td>
                    <?php else: ?>
                    <td class="value"><?php echo $_shipment['destination_company_name']; ?></td> </tr>
            <?php endif; ?>

                <tr>
                    <td class="label" colspan="2"><label><?php echo $this->__('Street'); ?></label></td>
                    <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                        <td class="value"><input type="text" id="destination_street" name="destination_street" value="<?php echo $_shipment['destination_street']; ?>" class="input-text" /></td>
                    <?php else: ?>
                    <td class="value"><?php echo $_shipment['destination_street']; ?></td></tr>
            <?php endif; ?>


                <tr>
                    <td class="label" colspan="2"><label><?php echo $this->__('Suburb'); ?></label></td>
                    <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                        <td class="value">
                            <input type="text" id="destination_city" name="destination_city" value="<?php echo $_shipment['destination_city']; ?>" class="input-text" />
                        </td>
                    <?php else: ?>
                    <td class="value"><?php echo $_shipment['destination_city']; ?></td></tr>
            <?php endif; ?>

                <tr>
                    <td class="label" colspan="2"><label><?php echo $this->__('Region'); ?></label></td>
                    <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                        <td class="value"><input type="text" id="destination_region" name="destination_region" value="<?php echo $_shipment['destination_region']; ?>" class="input-text" /></td>
                    <?php else: ?>
                    <td class="value"><?php echo $_shipment['destination_region']; ?></td></tr>
            <?php endif; ?>

                <tr>
                    <td class="label" colspan="2"><label><?php echo $this->__('Postcode'); ?></label></td>
                    <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                        <td class="value">
                            <input type="text" id="destination_postcode" name="destination_postcode" value="<?php echo $_shipment['destination_postcode']; ?>" class="pcs-field input-text" />
                        </td>
                    <?php else: ?>
                    <td class="value"><?php echo $_shipment['destination_postcode']; ?></td></tr>
            <?php endif; ?>

                <tr>
                    <td class="label" colspan="2"><label><?php echo $this->__('Country'); ?></label></td>
                    <td class="value">
                        <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                            <select id="destination_country" name="destination_country" class="select">
                                <?php foreach (Mage::getModel('directory/country')->getCollection()->toOptionArray() as $_country): ?>
                                    <option value="<?php echo $_country['value']; ?>" <?php if ($_country['value'] == $_shipment['destination_country']): ?> selected="selected"<?php endif;?>><?php echo $_country['label']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        <?php else: ?>
                            <?php echo Mage::getModel('directory/country')->load($_shipment['destination_country']); ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label" colspan="2"><label><?php echo $this->__('Phone'); ?></label></td>
                    <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                        <td class="value"><input type="text" id="destination_phone" name="destination_phone" value="<?php echo $_shipment['destination_phone']; ?>" class="input-text" /></td>
                    <?php else: ?>
                    <td class="value"><?php echo $_shipment['destination_phone']; ?></td></tr>
            <?php endif; ?>

                <tr>
                    <td class="label" colspan="2"><label><?php echo $this->__('Email'); ?></label></td>
                    <?php if ($_shipment['status'] == Candf_Customshipping_Model_System_Config_Backend_Shipment_Status::PENDING): ?>
                        <td class="value"><input type="text" id="destination_email" name="destination_email" value="<?php echo $_shipment['destination_email']; ?>" class="input-text" /></td>
                    <?php else: ?>
                    <td class="value"><?php echo $_shipment['destination_email']; ?></td></tr>
            <?php endif; ?>

            </table>
        </div>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Special Instructions'); ?></h4>
    </div>
    <div class="fieldset">
        <textarea name="specialinstructions" id="specialinstructions" style="width:425px;" ><?php echo $_shipment['specialinstructions']; ?></textarea>
    </div>
</div>


