<?php

$_shipment = $this->getShipment();
$orderid =$_shipment->getOrderId();
$order = Mage::getModel('sales/order')->load($orderid);
$getShippingAmount = $order->getShippingAmount();

$shipmentId = $_shipment->getId();
$customshippingmodel = Mage::getModel('customshipping/shipment')->load($shipmentId);
$finalshippingcost = $customshippingmodel->getShippingCost();

$additional_service_data = Mage::getModel('customshipping/shipmentadditional')->getCollection()
                               ->addFieldToFilter('order_id', array('in' =>array('in' => array($orderid))))->getData();

?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Shipment Status'); ?></h4>
    </div>
    <div class="fieldset">
        <div style="overflow:auto;">
            <table cellspacing="0" class="form-list">
                <tbody>
                <tr>
                    <td class="label"><label><?php echo $this->__('Shipment Status'); ?></label></td>
                    <td class="value"><strong><?php  echo $this->getCandfShipmentStatus(); ?></strong></td>
                </tr>

                <tr>
                    <td class="label"><label><?php echo $this->__('Carrier Selected by Customer'); ?></label></td>
                    <td class="value"><strong><?php  echo $this->getCustomerSelectedQuoteDescription(); ?></strong></td>
                </tr>

                <?php foreach ($this->getShipment()->getOptions() as $_option): ?>
                    <?php ?>
                    <tr>
                        <td class="label"><label><?php echo $_option->getName(); ?></label></td>
                        <td class="value"><strong><?php echo $_option->getLabel($_option->getForcedValue()); ?></strong></td>
                    </tr>
                <?php  endforeach; ?>
                <tr>
                    <td class="label"><label><?php echo $this->__('Shipping Paid by Customer'); ?></label></td>
                    <td class="value"><strong><?php echo $this->formatCurrency($getShippingAmount); ?></strong></td>
                </tr>

                <?php
                if(!empty($additional_service_data)) {
                    ?>
                    <tr>
                        <td colspan="2" class="label"><label><?php echo $this->__('Additional Services Selected by Customer'); ?></label></td>

                    </tr>
                    <?php
                    $totalAdditional = 0;
                    foreach($additional_service_data as $additional_services) {
                        $additionalServiceId = $additional_services['additional_shipment_id'];
                        $additional_services_collection = Mage::getModel('customshipping/additionalservices')->getCollection()
                            ->addFieldToFilter('id', array('in' =>array('in' => array($additionalServiceId))))->getData();

                        $additional_service_name = $additional_services_collection['0']['Carrier_Service_Description'];
                        $additional_service_charges = '$'.$additional_services_collection['0']['Carrier_Basic_Charge'];

                        $totalAdditional+= $additional_services_collection['0']['Carrier_Basic_Charge'];
                        ?>

                        <tr>
                            <td class="label"><label></label></td>
                            <td class="value"><strong><?php echo $additional_service_name .'   '. $additional_service_charges; ?></strong></td>
                        </tr>


                        <?php
                    }
                    ?>
                <?php
                }?>
                </tbody>
            </table>
        </div>
    </div>
</div>



